apiVersion: apps/v1
kind: Deployment
metadata:
  name: dslist-deployment
  labels:
    app: dslist
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dslist
  template:
    metadata:
      labels:
        app: dslist
    spec:
      containers:
      - name: dslist-app
        image: jnrenepont/dslist:latest
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "dev"
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://db:5432/dslist
        - name: SPRING_DATASOURCE_USERNAME
          value: "postgres"
        - name: SPRING_DATASOURCE_PASSWORD
          value: "2801190225"

